/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Hogar
 */
public class GUI_Informacion extends javax.swing.JPanel {

    /**
     * Creates new form GUI_Informacion
     */
    public GUI_Informacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_PlacaDelVehiculo = new javax.swing.JTextField();
        jt_CedulaDelDueno = new javax.swing.JTextField();
        jt_NombreDelDueno = new javax.swing.JTextField();
        jt_NumeroDeRegistro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Número de registro");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setText("Nombre del dueño");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setText("Cédula del Dueño");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setText("Placa del vehiculos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        add(jt_PlacaDelVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 210, -1));

        jt_CedulaDelDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_CedulaDelDuenoActionPerformed(evt);
            }
        });
        add(jt_CedulaDelDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 210, -1));

        jt_NombreDelDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NombreDelDuenoActionPerformed(evt);
            }
        });
        add(jt_NombreDelDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 210, -1));
        add(jt_NumeroDeRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NombreDelDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NombreDelDuenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NombreDelDuenoActionPerformed

    private void jt_CedulaDelDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_CedulaDelDuenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CedulaDelDuenoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jt_CedulaDelDueno;
    private javax.swing.JTextField jt_NombreDelDueno;
    private javax.swing.JTextField jt_NumeroDeRegistro;
    private javax.swing.JTextField jt_PlacaDelVehiculo;
    // End of variables declaration//GEN-END:variables
}
